"""Packer builder — builds cloneable templates from ISO.

Generates a Packer file (`packer.pkr.hcl`) that automates the installation of
an operating system (kickstart / preseed / autounattend) on the hypervisor and
leaves it ready as a template cloneable by Terraform.

Two builders depending on the hypervisor:
  - Standalone ESXi        -> vmware-iso  (remote_type = esx5)
  - vCenter / vSphere      -> vsphere-iso

The resulting template is registered under the name `server.image`, so that
the Terraform generation (clones from the template) works without intervention.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from infranix.config import InfraConfig
from infranix.models import Image


# ─────────────────────────── Kickstart (RHEL/Rocky/CentOS) ───────────────────────────

KICKSTART_TEMPLATE = """\
# Kickstart generated by InfraNix — unattended installation
lang en_US.UTF-8
keyboard us
timezone UTC
# Network: initial dhcp; the VM is cloned later with a static IP (customize)
network --bootproto=dhcp --device=link --activate
rootpw --iscrypted {{ .RootPasswordHash }}
# Base install (no GUI)
url --url="{{ .Mirror }}"
repo --name="baseos" --baseurl="{{ .Mirror }}/BaseOS"
repo --name="appstream" --baseurl="{{ .Mirror }}/AppStream"

%packages
@core
%end

%addon com_redhat_kdump --disable
%end

clearpart --all --initlabel
part /boot --fstype="xfs" --size=1024 --asprimary
part pv.01 --size=1 --grow
volgroup vg0 pv.01
logvol / --fstype="xfs" --name=root --vgname=vg0 --size=20480 --grow

services --enabled="NetworkManager,sshd,cloud-init,open-vm-tools"

# Enable SSH and cloud-init (dynamic key via cloud-init / customize)
%post
sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
systemctl enable sshd
systemctl enable open-vm-tools
%end

reboot
"""

PRESEED_TEMPLATE = """\
# Preseed generated by InfraNix — unattended installation (Ubuntu/Debian)
d-i debian-installer/locale string en_US
d-i keyboard-configuration/xkb-keymap select us
d-i time/zone string UTC
d-i netcfg/choose_interface select auto
d-i netcfg/get_hostname string {{ .HostName }}
d-i netcfg/get_domain string local
d-i mirror/country string manual
d-i mirror/http/hostname string {{ .Mirror }}
d-i mirror/http/directory string /ubuntu

d-i passwd/root-login boolean true
d-i passwd/root-password string {{ .RootPassword }}
d-i passwd/root-password-again string {{ .RootPassword }}
d-i passwd/user-fullname string admin
d-i passwd/username string admin
d-i passwd/user-password string {{ .RootPassword }}
d-i passwd/user-password-again string {{ .RootPassword }}

d-i partman/mount_style select uuid
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true

d-i pkgsel/include string openssh-server cloud-init open-vm-tools
d-i pkgsel/upgrade select none
d-i grub-installer/only_debian boolean true
d-i grub-installer/bootdev string default

d-i finish-install/reboot_in_progress note
"""

# ─────────────────────────── Packer HCL ───────────────────────────

PACKER_HCL = """\
# Generated by InfraNix — Packer build for template
packer {{
  required_plugins {{
    vmware = {{
      version = ">= 1.0.0, < 2.0.0"
      source  = "github.com/hashicorp/vmware"
    }}
  }}
}}

variable "vcpus" {{ default = {{ .VCPUS }} }}
variable "memory" {{ default = {{ .MEMORY }} }}

source "vmware-iso" "template" {{
  # ESXi connection (standalone)
  remote_type          = "esx5"
  remote_host          = "{{ .Host }}"
  remote_port          = 443
  remote_username      = "{{ .VMUser }}"
  remote_password      = "{{ .VMPassword }}"
  remote_datastore     = "{{ .Datastore }}"
  vnc_bind_address     = "0.0.0.0"

  # ISO
  iso_url           = "{{ .ISOPath }}"
  iso_checksum      = "none"

  # SSH connection for provisioning
  ssh_username      = "root"
  ssh_password      = "{{ .RootPassword }}"
  ssh_wait_timeout  = "60m"
  communicator      = "ssh"

  # VM settings
  vm_name           = "{{ .TemplateName }}"
  guest_os_type     = "{{ .GuestOSType }}"
  firmware          = "bios"
  cpus              = var.vcpus
  memory            = var.memory

  # Disk
  disk_size         = {{ .DiskSize }}

  # Boot
  {{ .CdBootPrompt }}
  boot_command = [
    {{ .BootCommands }}
  ]
  boot_wait         = "10s"
  shutdown_command   = "/sbin/halt -p"
}}

build {{
  sources = ["source.vmware-iso.template"]

  provisioner "shell" {{
    inline = [
      "echo 'Hostkeys && timesync'",
      "systemctl enable --now chronyd",
      "systemctl enable --now sshd",
      "systemctl enable --now cloud-init open-vm-tools",
    ]
  }}
}}
"""


class PackerBuilder:
    """Generates and runs a Packer build per image."""

    def __init__(self, config: InfraConfig, image: Image,
                 iso_path: str = "", mirror_base: str = ""):
        self.config = config
        self.image = image
        self.iso_path = iso_path
        self.mirror_base = mirror_base

    # ── Config helpers ──

    def _builder(self) -> str:
        # Standalone ESXi -> vmware-iso; vCenter -> vsphere-iso
        if self.config.hypervisor.lower() == "esxi":
            return "vmware-iso"
        return "vsphere-iso"

    def _connection_block(self) -> str:
        # For vmware plugin v2.x, remote ESXi connection uses these args
        return (
            "remote_type          = \"esx5\"\n"
            "remote_host          = \"{host}\"\n"
            "remote_port          = 443\n"
            "remote_username      = \"{user}\"\n"
            "remote_password      = \"{password}\"\n"
            "remote_cache         = true\n"
            "cache_datastore      = \"{datastore}\"\n"
            "vnc_over_websocket   = true\n"
            "insecure_connection  = true"
        ).format(host=self.config.host or "",
                 user=self.config.user or "root",
                 password=self.config.password or "",
                 datastore=self.config.datastore or "")

    def _datastore_block(self) -> str:
        if self._builder() == "vmware-iso":
            # already set in remote_datastore
            return ""
        return f"datastore = \"{self.config.datastore or 'datastore1'}\""

    def _firmware_block(self) -> str:
        return 'firmware = "bios"'

    def _guest_os_type(self) -> str:
        distro = self.image.distro.lower()
        if distro in ("rhel", "rocky", "centos"):
            return "rhel9_64Guest"
        if distro == "ubuntu":
            return "ubuntu64Guest"
        if distro == "debian":
            return "debian11_64Guest"
        return "other4xLinux64Guest"

    def _boot_commands(self) -> str:
        """Boot commands per distro (installer on the boot prompt)."""
        distro = self.image.distro.lower()
        # The <enter> and <tab> are Packer keycodes
        if distro in ("rhel", "rocky", "centos"):
            return (
                '"<tab> inst.text inst.ks=http://{{.HTTPIP}}:{{.HTTPPort}}/ks.cfg<enter><wait>"'
            )
        if distro in ("ubuntu", "debian"):
            return (
                '"<enter><wait><wait> install auto url=http://{{.HTTPIP}}:{{.HTTPPort}}/preseed.cfg<enter><wait>"'
            )
        return "\"<enter>\""

    def _cd_boot_prompt(self) -> str:
        # Rocky/CentOS: the ISO boots to a "boot:" prompt that must be waited for
        if self.image.distro.lower() in ("centos",):
            return 'boot_wait = "5s"'
        return ""

    def _mirror(self) -> str:
        return self.mirror_base or "http://localhost/"

    # ── Generation ──

    def generate(self, out_dir: Path, checksum: str = "none") -> Path:
        """Write packer.pkr.hcl + unattended installation templates."""
        out_dir.mkdir(parents=True, exist_ok=True)

        # unattended installation templates
        kspath = out_dir / "http" / "ks.cfg"
        preseed_path = out_dir / "http" / "preseed.cfg"
        (out_dir / "http").mkdir(parents=True, exist_ok=True)

        distro = self.image.distro.lower()
        rootpw = self.config.root_password or "infranix"
        if distro in ("rhel", "rocky", "centos"):
            kspath.write_text(
                self._render_ks(rootpw))
            boot_prompt = "ks.cfg"
        else:
            preseed_path.write_text(
                self._render_preseed(rootpw))
            boot_prompt = "preseed.cfg"

        # boot commands that use the http path
        boot_cmd = self._boot_commands().replace("ks.cfg", boot_prompt).replace(
            "preseed.cfg", boot_prompt)

        # Get network name from config
        network = self.config.network or "VM Network"
        datastore = self.config.datastore or "datastore1"
        disk_size = 40  # default GB for template

        hcl = (PACKER_HCL
               .replace("{{ .Builder }}", "vmware-iso")
               .replace("{{ .VCPUS }}", "2")
               .replace("{{ .MEMORY }}", "4096")
               .replace("{{ .Host }}", self.config.host or "localhost")
               .replace("{{ .VMUser }}", self.config.user or "root")
               .replace("{{ .VMPassword }}", (self.config.password or "").replace("%29", ")"))
               .replace("{{ .ISOPath }}", self.iso_path or "/tmp/image.iso")
               .replace("{{ .RootPassword }}", rootpw)
               .replace("{{ .Datastore }}", datastore)
               .replace("{{ .Network }}", network)
               .replace("{{ .Host }}", self.config.host or "localhost")
               .replace("{{ .DiskSize }}", str(disk_size))
               .replace("{{ .GuestOSType }}", self._guest_os_type())
               .replace("{{ .TemplateName }}", self.image.name)
               .replace("{{ .CdBootPrompt }}", self._cd_boot_prompt())
               .replace("{{ .BootCommands }}", boot_cmd))
        # collapse structural HCL braces ({{ }} -> { })
        hcl = hcl.replace("{{", "{").replace("}}", "}")
        (out_dir / "packer.pkr.hcl").write_text(hcl)
        return out_dir

    def _render_ks(self, rootpw: str) -> str:
        import hashlib
        # simple MD5 hash (kickstart compatible) — real: use openssl passwd -6
        import crypt
        hashed = crypt.crypt(rootpw, crypt.mksalt(crypt.METHOD_SHA512))
        return (KICKSTART_TEMPLATE
                .replace("{{ .RootPasswordHash }}", hashed)
                .replace("{{ .Mirror }}", self._mirror()))

    def _render_preseed(self, rootpw: str) -> str:
        return (PRESEED_TEMPLATE
                .replace("{{ .HostName }}", self.image.name)
                .replace("{{ .RootPassword }}", rootpw)
                .replace("{{ .Mirror }}", self._mirror()))

    # ── Execution ──

    def build(self, work_dir: Path) -> bool:
        """Run `packer build` in the generated directory."""
        import subprocess
        env = dict()
        env.update({"PACKER_LOG": "0"})
        res = subprocess.run(["packer", "init", "."], cwd=str(work_dir),
                             capture_output=True, text=True, timeout=120)
        if res.returncode != 0:
            print(f"packer init: {res.stderr}")
            return False
        res = subprocess.run(["packer", "build", "packer.pkr.hcl"],
                             cwd=str(work_dir), capture_output=True, text=True,
                             timeout=3600)
        print(res.stdout[-3000:])
        if res.returncode != 0:
            print(f"packer build failed: {res.stderr[-3000:]}")  # noqa: E501
            return False
        return True
